
name: download-node-and-run-code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   
      - run: node -v
      - name: Script
        run: ./runtest.ps1
        shell: pwsh

  